import './globals.scss';
import ServiceWorkerRegistration from '@/components/ServiceWorkerRegistration/ServiceWorkerRegistration';

export const viewport = {
  width: 'device-width',
  initialScale: 1.0,
  themeColor: '#333',
};

export const metadata = {
  title: 'La Podrida App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
  manifest: '/manifest.json',
  appleWebAppCapable: 'yes',
  appleWebAppStatusBarStyle: 'default',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body>
        <ServiceWorkerRegistration />
        {children}
      </body>
    </html>
  );
}
