import './globals.scss';
import ServiceWorkerRegistration from '@/components/ServiceWorkerRegistration/ServiceWorkerRegistration';
import Auth0ClientProvider from '@/components/Auth0ClientProvider/Auth0ClientProvider';

export const viewport = {
  width: 'device-width',
  initialScale: 1.0,
  maximumScale: 1.0,
  userScalable: 'no',
  themeColor: '#333',
};

export const metadata = {
  title: 'La Podrida App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
  manifest: '/manifest.json',
  appleWebAppCapable: 'yes',
  appleWebAppStatusBarStyle: 'default',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ServiceWorkerRegistration />
        <Auth0ClientProvider>{children}</Auth0ClientProvider>
      </body>
    </html>
  );
}
