import './globals.scss';
import { SpeedInsights } from '@vercel/speed-insights/next';

export const metadata = {
  title: 'La Podrida App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
